### ISSUE TITLE
feature requests

### ISSUE THREAD

**Issue by jsarenik** [nwtgck/piping-chat-web#131]
Putting down some of my thoughts and waiting for feed-back to see if my thoughts are better fit for a custom fork or would be accepted generally.

 1. No external assets (currently there are some css files being loaded from 
 1. Send message on ENTER (or at least CTRL+ENTER)

**Comment by nwtgck** [comment]
Thanks again @jsarenik! I think <kbd>ctrl</kbd> + <kbd>enter</kbd> is a good idea too. In macOS, it should be <kbd>cmd</kbd> + <kbd>enter</kbd>. 

I'm not sure the meaning of "1 No external assets".  Could you explain it more?

**Comment by jsarenik** [comment]
Sure. I will explain.

1. Open a new tab in Chromiuml/Chrome (note that `piping-chat-web` does not work in Firefox)
1. Open Developer Tools, Network tab.
1. In browser tab open https://xn--jrok-loa.bublina.eu.org/chat/ (which is a build of `piping-chat-web` with some updates and a changed `serverUrl` of the piping-server. See https://github.com/jsarenik/piping-chat-web/tree/jsn/bublina)
1. Look into the list of 6 assets loaded. See mine below.

```
https://xn--jrok-loa.bublina.eu.org/chat/
https://d33wubrfki0l68.cloudfront.net/bundles/df13aee16387d94666662df35e6f9d3b4d7980f2.js
https://d33wubrfki0l68.cloudfront.net/308ee3580a4a34bd230025d460762d53b5344efc/b5f29/chat/fonts/materialicons-regular.0509ab09.woff2
https://xn--jrok-loa.bublina.eu.org/chat/manifest.json
https://xn--jrok-loa.bublina.eu.org/chat/img/icons/favicon-32x32.png
https://xn--jrok-loa.bublina.eu.org/chat/img/icons/android-chrome-192x192.png
```

The only external resources are second and third.
The second line points to `vuejs` and the third line points to `materialicons` font.
Both can be made local so that they will not be loaded from cloudfront.net.
Then piping-chat-web can be used even in evironments with no access to cloudfront.net.

**Comment by jsarenik** [comment]
By the way, there is one other change done to https://xn--jrok-loa.bublina.eu.org/chat/. https://github.com/jsarenik/jekyll/commit/c25d1fdb7bca72059992fc60ac16d5d93790eb78

**Comment by jsarenik** [comment]
> Thanks again @jsarenik! I think ctrl + enter is a good idea too. In macOS, it should be ctrl + cmd.

CMD+ENTER

**Comment by nwtgck** [comment]
@jsarenik 
Thanks. "1 No external assets" means you propose piping-chat-web should not load external resources. Is it right?

**Comment by jsarenik** [comment]
Yes. It would be definitely great as an option at least (I mean without manual editing which is possible even now if I was able able to see that URL with `cloudfront.net` somewhere inside the generated files. My guess is that `js/chunk-vendors.17861028.js` is doing the magic...).

Thank you @nwtgck

**Comment by nwtgck** [comment]
@jsarenik 
I think I can remove external assets. Actually, another project using Piping Server, [Piping UI](https://github.com/nwtgck/piping-ui-web) is independent of external assets. Piping UI never accesses to external assets such as icons and [Workbox](https://developers.google.com/web/tools/workbox) for higher privacy/security purposes, but icons and PWA (Workbox) are available. So, I may implement the feature to use the knowledge from the development probably.


You can create two new issues for 1 and 2. Then, I will close this issue. Of course, I will create issues instead of you when you don't create.

**Comment by jsarenik** [comment]
> You can create two new issues for 1 and 2. Then, I will close this issue. Of course, I will create issues instead of you when you don't create.

Sure, I will do it. Thank you!

**Comment by jsarenik** [comment]
Closing in favor of #133 and #134
