### ISSUE TITLE
Use only local assets

### ISSUE THREAD

**Issue by jsarenik** [nwtgck/piping-chat-web#133]
As noted in https://github.com/nwtgck/piping-chat-web/issues/131#issuecomment-567074297

For higher privacy/security reasons it would be beneficial to use only local assets instead of fetching font/css/js from other servers on the clear internet (e.g. cloudfront.net).

**Comment by jsarenik** [comment]
As for me, this is already fixed. Using ef55f42 now at https://a.bublina.eu.org/chat
Thank you @nwtgck !!!

**Comment by jsarenik** [comment]
@nwtgck Apologies, the external assets were actually caused by my Netlify settings. So everything was OK ever before.

**Comment by nwtgck** [comment]
@jsarenik Great!

But, Is it already fixed? I think Service Worker still uses Google assets, WorkBox.

```js
importScripts("https://storage.googleapis.com/workbox-cdn/releases/4.3.1/workbox-sw.js");
```
(<https://piping-chat.netlify.com/service-worker.js>)


For example, in another similar project, it uses local WorkBox JavaScript. I'm going to use the same configuration for this project too.

```js
importScripts("precache-manifest.97213ef79079d106e77e95afb42d6a54.js", "workbox-v4.3.1/workbox-sw.js");
```
(<https://piping-ui.org/service-worker.js>)

**Comment by jsarenik** [comment]
@nwtgck Good point! Thank you for mentioning the `workbox-sw.js` as I did not notice it myself.

So far I have manually edited https://xn--jrok-loa.bublina.eu.org/chat/service-worker.js and so far so good.

Thank you!
